### ISSUE TITLE
KeyError: 'id' when trying to parse specific RSS feed

### ISSUE THREAD

**Issue by pavelcarcass** [ckpunk/feederek#1]
When trying to work with [this](http://baikalinform.ru/obyavki-rss) feed, the bot drops following error:
-----Last feeds---
Traceback (most recent call last):
  File "feederek.py", line 38, in <module>
    feederek()
  File "feederek.py", line 22, in feederek
    fee_links.append(fee['entries'][x]['id'])
  File "/home/xxxxxx/.local/lib/python3.5/site-packages/feedparser.py", line 357, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'id'

**Comment by pawlikowsky** [comment]
@pavelcarcass 
Hi,
I just checked this. I'm using Python 3.6 but everything is working just fine. Are you using feedparser 5.2.1?  Try this code (You can use my bot token and channel for testing, I don't using it anymore), and check on https://t.me/cybersecpl

```python
import feedparser
import pickle
import telegram
import sys
from time import sleep

feed_list =["http://baikalinform.ru/obyavki-rss",
            ]

last_feeds = pickle.load(open("db.p", 'rb'))
fee_links = []

bot = telegram.Bot(token='228955506:AAGmwy8-a7b5PKjuZjiPk_7OJ0kJ6LiHBvM')

print(last_feeds)
print("-----Last feeds---")

def feederek():
    for i in feed_list:
        fee = feedparser.parse(i)
        fee_title = fee.feed.title
        for x in range(5):
            fee_links.append(fee['entries'][x]['id'])
            if fee['entries'][x]['id'] in last_feeds:
                print("Nothing new - " + fee_title)
            else:
                sleep(5) # for server flood detection
                entry_title = fee['entries'][x]['title']
                entry_id = fee['entries'][x]['id']
                print("Updated - " + fee_title)


                message = str(fee_title +"\n" + entry_title +"\n" + entry_id)
                bot.sendMessage(chat_id="@CyberSecPL", text=message)

    pickle.dump(fee_links, open("db.p", 'wb'))
    sys.exit()

if __name__ == "__main__":
    feederek()
```

No error here
https://i.imgur.com/dDVpgyl.png

**Comment by pavelcarcass** [comment]
Thank you for your response, Mateusz. Yes, that feed works with Feederek without errors, but it's just because I found the workaround and made some changes in the feed. The fact is that if there's no `<guid>` elements in the feed, the bot drops abovementioned error. I added `<guid>`'s in the feed and everything goes fine now.

Thank you for such a useful bot.

**Comment by pawlikowsky** [comment]
Thank you for your kind words, I'm glad you like it. If you have any problems with it in the future, you can always contact me.

**Comment by pavelcarcass** [comment]
Hi Mateusz! As you maybe know, the Telegram will be most likely blocked in Russia in the nearest future. I'm ready for that, just found an access to good remote Socks5 proxy to connect to Telegram. But how do I set up my bots to use that proxy?

**Comment by pawlikowsky** [comment]
Hi Pavel. Yes I've heard about that. This is very bad information. I think python-telegram-bot have support for proxy connections, or if not, there will be one soon ;). I could try do something with this but already have some work related issues to solve. So I need couple of days (maybe one week) to do this. I hope it is fine with you.

**Comment by pavelcarcass** [comment]
Yes, sure. I'll wait as long as you need.

**Comment by pavelcarcass** [comment]
I've found the solution:

```
import pickle
import feedparser
import telegram
from time import sleep

feed_list =["http://your_rss_url",
]

last_feeds = pickle.load(open("/path-to-bot/db.p", 'rb'))
fee_links = []

SOCKS_URL="socks5://your_socks_address:your_socks_port"
SOCKS_USER="your_socks_login"
SOCKS_PASS="your_socks_password"

proxed_request = telegram.utils.request.Request(proxy_url = SOCKS_URL, urllib3_proxy_kwargs = {'username': SOCKS_USER, 'password': SOCKS_PASS,}, read_timeout=20)
bot = telegram.Bot(token='your_bot_token', request=proxed_request)

print(last_feeds)
print("-----Last feeds---")

def feederek():
for i in feed_list:
fee = feedparser.parse(i)
fee_title = fee.feed.title
for x in range(5):
fee_links.append(fee['entries'][x]['id'])
if fee['entries'][x]['id'] in last_feeds:
print("Nothing new - " + fee_title)
else:
sleep(5)
entry_title = fee['entries'][x]['title']
entry_id = fee['entries'][x]['id']
print("Updated - " + fee_title)

            message = str(entry_title +"\n" + entry_id)
            bot.sendMessage(chat_id="@your_channel", text=message)

pickle.dump(fee_links, open("/path-to-bot/db.p", 'wb'))
return
feederek()
```

**Comment by pawlikowsky** [comment]
Hi Pavel. I'm very sorry that I wasn't able to fix this for you on time. I didn't forget, just had yeasterday harsh deadline in new work. You solution is really nice, good job! Only one thing. Last night I get message from telegram bot devs that they update library and fix some issues  with urlib3 for socks5 in telegram library. Keep this in mind.

>We've just released v10.1.0!
> As always, upgrade using pip install -U python-telegram-bot
> Fixes changing previous behaviour:
> - Add urllib3 fix for socks5h support (#1085)
> - Fix send_sticker() timeout=20 (#1088)
> Fixes:
> - Add a caption_entity filter for filtering caption entities (#1068)
> - Inputfile encode filenames (#1086)
> - InputFile: Fix proper naming of file when reading from subprocess.PIPE (#1079)
> - Remove pytest-catchlog from requirements (#1099)
> - Documentation fixes (#1061, #1078, #1081, #1096)
> We wish to thank everyone who had contributed to this release. Happy upgrades everyone!
