### ISSUE TITLE
'Bad Request: can\'t parse entities: Unsupported start tag "p" at byte offset 39'

### ISSUE THREAD

**Issue by eikoninaru** [ckpunk/feederek#2]
Hi there!
When try to grab https://www.archlinux.org/feeds/news/ whith` parse_mode=ParseMode.HTML` got this error:
```
Traceback (most recent call last):
  File "/home/lesya/feederek/feederek.py", line 44, in <module>
    feederek()
  File "/home/lesya/feederek/feederek.py", line 38, in feederek
    bot.sendMessage(chat_id="-100xxx", text=message, parse_mode=ParseMode.HTML, disable_notification=True)
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/bot.py", line 151, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 202, in post
    result = self._request_wrapper(
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 152, in _request_wrapper
    raise BadRequest(repr(message))
telegram.error.BadRequest: 'Bad Request: can\'t parse entities: Unsupported start tag "p" at byte offset 39'
```

**Comment by pawlikowsky** [comment]
Hi @eikoninaru 
It was long time since I looked on feederek last time. I'm surprised that someone is still using it. Try to use `parse_mode="HTML"`. 

Feederek is my old and outdated script, `telegram` library used in feederek is also not supported for years and source was removed from GitHub. I strongly recommend to look for better similar tool, which is maintained and updated. Maybe I will find some time to create feederek 2.0 someday :)

**Comment by eikoninaru** [comment]
_> Try to use parse_mode="HTML"_

the same issue:
```
-----Last feeds---
Updated - Arch Linux: Recent news updates
Traceback (most recent call last):
  File "/home/lesya/feederek/feederek.py", line 45, in <module>
    feederek()
  File "/home/lesya/feederek/feederek.py", line 38, in feederek
    bot.sendMessage(chat_id="-1001223295074", text=message, parse_mode="HTML", disable_notification=True)
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/bot.py", line 125, in decorator
    result = func(self, *args, **kwargs)
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/bot.py", line 151, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 202, in post
    result = self._request_wrapper(
  File "/home/lesya/.local/lib/python3.9/site-packages/telegram/utils/request.py", line 152, in _request_wrapper
    raise BadRequest(repr(message))
telegram.error.BadRequest: 'Bad Request: can\'t parse entities: Unsupported start tag "p" at byte offset 38'
```
btw, in other case it works smoothly!

**Comment by pawlikowsky** [comment]
@eikoninaru  I just tested this on my local env. I only updated feedparser to newest version and this it working for me (with parse_mode="HTML"). I updated requirements file in repository also. 

https://imgur.com/a/t8pcJAI

**Comment by eikoninaru** [comment]
@zimmermannpl I slightly changed the standard message format.
here is my feederek.py
```
import pickle
import sys
from time import sleep

import feedparser
import telegram

feed_list =["https://www.archlinux.org/feeds/news/",
            ]

last_feeds = pickle.load(open("db.p", 'rb'))
fee_links = []

bot = telegram.Bot(token='YOUR_TOKEN')

print(last_feeds)
print("-----Last feeds---")

def feederek():
    for i in feed_list:
        fee = feedparser.parse(i)
        fee_title = fee.feed.title
        for x in range(2):
            fee_links.append(fee['entries'][x]['id'])
            if fee['entries'][x]['id'] in last_feeds:
                print("Nothing new - " + fee_title)
            else:
                sleep(5) # for server flood detection
                entry_title = fee['entries'][x]['title']
                entry_id = fee['entries'][x]['id']
                entry_summary = fee['entries'][x]['summary']
                entry_link= fee['entries'][x]['link']
                print("Updated - " + fee_title)


                message = str("<b>" + entry_title + "</b>" +"\n" +"\n" + entry_summary +"\n" +"\n" + entry_link)
                bot.sendMessage(chat_id="@CHANNEL_NAME", text=message, parse_mode="HTML", disable_notification=True)

    pickle.dump(fee_links, open("db.p", 'wb'))
    sys.exit()

if __name__ == "__main__":
    feederek()
```

it stuck if `entry_summary` is enabled

**Comment by pawlikowsky** [comment]
Ohh now I get it. I'm afraid  we can't do anything with that. You see this isn't feederek problem but specification of Telegram API. They don't support these html tags in message body (see: https://imgur.com/a/z06QrVG) Docs: https://core.telegram.org/bots/api#html-style . Only way is to strip all html tags from entry_summary string and rebuild message with only supported tags. This can be tricky. You can also try to use `markdownify` create string with markdown and use `MarkdownV2` parser mode. But also look on Telegram API docs for markdown v2 (https://core.telegram.org/bots/api#markdownv2-style), lots of limitations with special characters and escaping for parsing. So extra work for handling characters escaping is needed and this can be tricky too.  I don't think there is an easier way to do it.

**Comment by eikoninaru** [comment]
```
import telegram
from markdownify import markdownify as md

feed_list =["https://www.archlinux.org/feeds/news/",
            ]
...

 message = str(md("*" + entry_title + "*" +"\n" +"\n" + entry_summary + entry_link))
...
```
works fine! thank you!
